import React, { Component } from "react";

import { Nav, NavList, NavItem, NavLink } from "./Styled";

export const Menu = ({ onLinkClick }) => {
  return (
    <Nav>
      <NavList>
        <NavItem>
          <NavLink
            onClick={onLinkClick}
            exact
            to="/"
            activeClassName="router-link--active"
          >
            ГЛАВНАЯ
          </NavLink>
        </NavItem>
        <NavItem>
          <NavLink
            onClick={onLinkClick}
            to="/club"
            activeClassName="router-link--active"
          >
            КЛУБ
          </NavLink>
        </NavItem>
        <NavItem>
          <NavLink
            onClick={onLinkClick}
            to="/karaoke"
            activeClassName="router-link--active"
          >
            КАРАОКЕ
          </NavLink>
        </NavItem>
        <NavItem>
          <NavLink
            onClick={onLinkClick}
            to="/craft"
            activeClassName="router-link--active"
          >
            КРАФТ-БАР
          </NavLink>
        </NavItem>
        <NavItem>
          <NavLink
            onClick={onLinkClick}
            to="/party"
            activeClassName="router-link--active"
          >
            АФИША
          </NavLink>
        </NavItem>
        <NavItem>
          <NavLink
            onClick={onLinkClick}
            to="/deal"
            activeClassName="router-link--active"
          >
            АКЦИИ
          </NavLink>
        </NavItem>
        <NavItem>
          <NavLink
            onClick={onLinkClick}
            to="/banket"
            activeClassName="router-link--active"
          >
            БАНКЕТЫ
          </NavLink>
        </NavItem>
        <NavItem>
          <NavLink
            onClick={onLinkClick}
            to="/menu"
            activeClassName="router-link--active"
          >
            МЕНЮ
          </NavLink>
        </NavItem>
        <NavItem>
          <NavLink
            onClick={onLinkClick}
            to="/photo"
            activeClassName="router-link--active"
          >
            ФОТО
          </NavLink>
        </NavItem>
        <NavItem>
          <NavLink
            onClick={onLinkClick}
            to="/contacts"
            activeClassName="router-link--active"
          >
            КОНТАКТЫ
          </NavLink>
        </NavItem>
      </NavList>
    </Nav>
  );
};

export default Menu;
